# Generated by Django 3.1.6 on 2021-03-15 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nick', models.CharField(max_length=30)),
                ('introduce', models.TextField()),
                ('phone_num', models.CharField(max_length=11)),
                ('is_promoter', models.CharField(choices=[('P', 'Promoter'), ('I', 'Influencer')], max_length=1)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('IR', 'Irelevance')], max_length=2)),
                ('age', models.CharField(choices=[('10S', '10s'), ('20S', '20s'), ('30S', '30s'), ('40S', '40s'), ('50S', '50s'), ('60S', '60s'), ('IR', 'Irelevance')], max_length=3)),
                ('cost', models.CharField(choices=[('1MD', '1m'), ('10M', '10m'), ('1BU', '1b'), ('IR', 'Irelevance')], max_length=3)),
                ('field', models.CharField(choices=[('F&B', 'Foods and Bevarage'), ('L&S', 'Leisure and Sports'), ('B&C', 'Beauty and Cosmetics'), ('IR', 'Irelevance')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebda.account')),
                ('like', models.ManyToManyField(blank=True, related_name='like_promoter', to='celebda.Account')),
                ('matchcon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebda.matchcondition')),
            ],
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=30)),
                ('introduce', models.CharField(max_length=200)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebda.account')),
                ('like', models.ManyToManyField(blank=True, related_name='like_influencer', to='celebda.Account')),
                ('matchcon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celebda.matchcondition')),
            ],
        ),
    ]
