# Generated by Django 3.1.6 on 2021-03-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
