# Generated by Django 3.1.6 on 2021-03-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebda', '0003_auto_20210323_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='thum',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
