# Generated by Django 3.1.6 on 2021-03-23 07:30

import celebda.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('celebda', '0004_account_thum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='thum',
            field=imagekit.models.fields.ProcessedImageField(upload_to=celebda.models.account_thum_path),
        ),
    ]
